head.load("js/lib/jquery.js",
					"js/lib/custom.js",
					"js/lib/slick.min.js",
					"js/lib/bootstrap.min.js",
					"js/lib/fancybox.js",
					"js/lib/smoothscroll.js",
					"js/lib/mCustomScrollbar.min.js",
					"js/lib/map.js",
					"js/common.js");
